version: '3.1'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: ${DOMAINNAME:?err}
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    environment:
      - DMS_DEBUG=1
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - ./config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    dns: 1.1.1.1
    restart: always

  mega-create:
    container_name: mega
    build:
      context: upload
    environment:
      DOMAINNAME: ${DOMAINNAME:?err}
      CREDENTIALS: ${CREDENTIALS:?err}
    volumes:
      - maildata:/var/mail
      - ./config/:/email-config/
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mega.rule=Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.mega.entrypoints=web-secure"
      - "traefik.http.routers.mega.tls.certresolver=letsencrypt"
      - "traefik.http.services.mega.loadbalancer.server.port=8080"

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local

networks:
  traefik:
    external: true