version: '3'
services:
    mysqldb:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ROOT_HOST=%
        volumes:
          - ./data:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        build:
          context: .
          args:
            dom: ${DOMAIN}