version: '3.1'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: ${DOMAINNAME:?err}
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - ./config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    dns: 1.1.1.1
    restart: always

  mega-create:
    container_name: mega
    build:
      context: upload
    ports:
      - "8980:8080"
    environment:
      DOMAINNAME: ${DOMAINNAME:?err}
      CREDENTIALS: ${CREDENTIALS:?err}
    volumes:
      - maildata:/var/mail
      - ./config/:/email-config/
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mega.rule=Host(`${DOMAINNAME}`)"
      - "traefik.http.routers.mega.entrypoints=websecure"
      - "traefik.http.routers.mega.tls.certresolver=myresolver"
      - "traefik.http.services.mega.loadbalancer.server.port=8080"

#  traefik:
#    image: "traefik:v2.2"
#    container_name: "traefik"
#    command:
##      - "--api.insecure=true"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.websecure.address=:443"
#      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
#      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
#      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
#    ports:
#      - "443:443"
##      - "8080:8080"
#    volumes:
#      - "./letsencrypt:/letsencrypt"
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local