version: '3.1'
services:
  mega-create:
    image: maxisme/mega-create
    domainname: ${DOMAINNAME:?err}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./config/:/tmp/docker-mailserver/
    env_file:
      - .env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

  sshd:
    image: maxisme/sshd:latest
    volumes:
      - "~/.ssh:/root/.ssh"
    ports:
      - "3307:22"