version: '3.1'
services:
  mega-create:
    image: maxisme/mega-create:latest
    env_file:
      - ".env"
    volumes:
      - ./mail/:/var/mail
      - ./config/:/email-config/
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mega.rule=Host(`${DOMAINNAME}`)"
        - "traefik.http.routers.mega.entrypoints=web-secure,web"
        - "traefik.http.routers.mega.tls.certresolver=letsencrypt"
        - "traefik.http.services.mega.loadbalancer.server.port=8080"
      placement:
        constraints: [node.role == manager]

networks:
  traefik:
    external: true